### ISSUE TITLE
Double multiplication signs add to tokens for exponents

### ISSUE THREAD

**Issue by rachelriv** [alexschneider/teascript#47]

**Comment by juansc** [comment]
Question: What should be the precedence of `**` be? We might need to create a new expression and stuff it between multiplication and prefix unary. In Python for example, the `**` operator binds more tightly than unary operators on the left, but less tightly than a unary operator on the right.

``` python
-2**10   # This is -1024, not 1024
4**-2     # This is 1/(16) = 4^(-2)
```

What about these cases?

``` python
++x**3
3**++x
x++**3
3**x++
```

These all seem perfectly legitimate code.

**Comment by rtoal** [comment]
In Ruby, Python, Lua, and Ada, exponentiation has higher precedence than prefix negation. This is perhaps, because of the way traditional arithmetic is rendered where exponentiation is a superscript.

None of these languages have the ++ or -- side-effect increment/decrement operators. And those languages that do have them (e.g. Java, JavaScript, the C family, etc.) don't have exponentiation. I think what you guys can do is go research a bunch of programming languages and see which ones have BOTH exponentation and the (IMHO stupid) side-effecting incrementers and see how _they_ do it.

If you do find such a language (that has both) let me know what it is.

My preference (but don't listen to me, because this is _your_ language, not mine) is to ditch the `++` and `--`. Those things are useless, confusing, and modern compilers are smart enough to take advantage of hardware autoincrementing and autodecrementing where they exist.
